---
apiVersion: v1
kind: Pod
metadata:
  name: app
  namespace: default
spec:
  containers:
   - image: busybox
     name: myapp
     command:
        - sleep
        - "3600"
     imagePullPolicy: IfNotPresent
     env:
      - name: PGHOST
        valueFrom:
         configMapKeyRef:
          name: postgres-db-conn-cm
          key: "postgres-db-host"
      - name: PGPORT
        valueFrom:
         configMapKeyRef:
          name: postgres-db-conn-cm
          key: "postgres-db-port"
      - name: PGUSER
        valueFrom:
         configMapKeyRef:
          name: postgres-db-conn-cm
          key: "postgres-db-user"
      - name: PGPASSWORD
        valueFrom:
          secretKeyRef:
           name: "postgres-password"
           key: password