---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: external-secret
spec:
  # Checking for updates
  refreshInterval: 10m # is set to 0 to prevent from being automatically updated

  # Name of the Secret Store
  secretStoreRef:
    name: eso-service-account  
    kind: ClusterSecretStore

  # The secret that will be created in k8s
  target:
    name: pgpassword
    creationPolicy: Owner
  
  # Name of the secret in secret manager
  dataFrom:
  - extract:
      key: postgres-secrets-two